
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.98.0
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=6"
      - "-search.latencyOffset=0s"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8428/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    command:
      - -retentionPeriod=400d
    ports:
      - "9428:9428"
      - "9899:9899"
    restart: unless-stopped
