
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.98.0
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=6"
      - "-search.latencyOffset=0s"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8428/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    command:
      - -retentionPeriod=400d
    ports:
      - "9428:9428"
      - "9899:9899"
    restart: unless-stopped
  wp-monitor:
    image: ghcr.io/wp-labs/wp-monitor:0.3.10-alpha
    container_name: wp-monitor
    restart: unless-stopped
    ports:
      - "18080:18080"
    environment:
      APP_CONFIG_PATH: config/app.toml
    volumes:
      - ./config/app.toml:/app/config/app.toml:ro
